My new branch for task5
KalashM/TestNewProject pull request #1
Opened 2023-04-01 14:03 UTC by KalashM

The initial version of solution for dining philisophers problem.

2023-04-17 18:35 UTC, davydov-vyacheslav requested changes

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/java/com/example/diningphilosophers/Philosopher.java
> +    private static final Semaphore SEMAPHORE = new Semaphore(4);
почему 4 ?

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/java/com/example/diningphilosophers/Demo.java
> +    public static Philosopher[] createPhilosophers(int n) {
Лучше этот метод перенести в отдельный класс "застолье"

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/java/com/example/diningphilosophers/Demo.java
> +        Philosopher[] philosophers = new Philosopher[n];
почему массивы? в Java мире List всему голова ...

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/java/com/example/diningphilosophers/Fork.java
> +    private int philosopherUsingThisFork;
по хорошему, тут полем класса должно быть "Философ". Если он есть - мы знает и его ид, и изФри = фолс, ну и наоборот .... если нуля - значит вилка свободна

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/java/com/example/diningphilosophers/Philosopher.java
> +        System.out.println(Thread.currentThread().getName() + " is running for philosopher " + id);
старайся не использовать System.out.println , а вместо него логирование

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/java/com/example/diningphilosophers/Philosopher.java
> +    private int id;
Каждый философ может либо есть, либо размышлять

это состояние философа тоже было бы хорошо описать

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/java/com/example/fileloader/FileLoader.java
> +import java.io.*;
не используй звездочки 
![](https://i.stack.imgur.com/94GRg.png)

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/java/com/example/fileloader/FileLoaderDemo.java
> +    private static final String LOCATION = "D:\\downloads\\Task5Downloads\\";
используй относительные пути

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/java/com/example/fileloader/FileLoader.java
> +    public void downloadFromURL(String url) {
у тебя url - и поле класса, и аргумент метода .. что-то тут не так

2023-04-17 18:35 UTC, davydov-vyacheslav commented on task5/src/main/resources/ReadMe.txt
> +1. Надо реализовать решение задачи обедающих философов. https://ru.wikipedia.org/wiki/Задача_об_обедающих_философах.
файлы с описанием кладутся в корень проекта (в твоем случае task5), и в markdown формате

2023-04-18 07:57 UTC, KalashM commented on task5/src/main/java/com/example/diningphilosophers/Philosopher.java
> +    private static final Semaphore SEMAPHORE = new Semaphore(4);
Чтобы избежать дедлока, елси философов будет 5. Чтобы не было такого, что каждый возьмет одну видку и ждёт.

2023-04-18 08:03 UTC, KalashM commented on task5/src/main/java/com/example/diningphilosophers/Demo.java
> +        Philosopher[] philosophers = new Philosopher[n];
Так как точно известно количество филососфов и оно не изменяется в процессе выполнения, то решила использовать массив.

2023-04-18 08:04 UTC, KalashM commented on task5/src/main/java/com/example/diningphilosophers/Fork.java
> +    private int philosopherUsingThisFork;
Надо подумать :)

2023-04-18 08:08 UTC, KalashM commented on task5/src/main/java/com/example/diningphilosophers/Demo.java
> +    public static Philosopher[] createPhilosophers(int n) {
ОК :)

2023-04-18 08:09 UTC, KalashM commented on task5/src/main/java/com/example/diningphilosophers/Philosopher.java
> +        System.out.println(Thread.currentThread().getName() + " is running for philosopher " + id);
Да. Добавлю логирование.

2023-05-04 19:58 UTC, merged